global:
  env: dev
  helmDefault: true
  valuesFile: istio-dependencies/values-test.yaml
  spec:
    project: istio-desv
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    source:
      repoURL: https://github.com/inderspoc/istio-setup.git
      targetRevision: HEAD

argocdApplications:
  istio:
    disableAutomated: false
    disable: false
    name: istio
    namespace: argocd
    source_path: "."
    project: istio-dev


